-- 用户信息表 MB_USER_INFO
-- 删除表 DROP TABLE MB_REMIT_REC CASCADE CONSTRAINTS;
CREATE TABLE MB_USER
(
  ID      NVARCHAR2(36) NOT NULL,
  PHONE   NVARCHAR2(16) UNIQUE NOT NULL,
  PASSWORD NVARCHAR2(32) NOT NULL,
  USERNAME NVARCHAR2(32) ,
  CARDID   NVARCHAR2(18),
  NICKNAME NVARCHAR2(16),
  GENDER   NVARCHAR2(2) CONSTRAINT CHK_USER_GENDER CHECK (GENDER IN ('男','女')),
  ADDRAREA NUMBER ,
  ADDRSTREET NVARCHAR2(64) ,
  EMAIL       NVARCHAR2(32) UNIQUE,
  CREATEDATE  DATE DEFAULT SYSDATE,
  UNLOCKDATE  DATE,
  STATUS      NUMBER(2) DEFAULT 0,
  LASTLOGINDATE         DATE,
  LOGINCOUNT        NUMBER,
  LOGINIP           NVARCHAR2(16),
  BINDINGBUSINESS   NVARCHAR2(36),
  ISLOADPIC    NUMBER(1) DEFAULT 0,
  CONSTRAINTS PK_USER_INFO PRIMARY KEY(ID) USING INDEX TABLESPACE tbs_pk_idx
);
/


--用户角色表 MB_USER_ROLE
-- 删除表 DROP TABLE MB_USER_ROLE CASCADE CONSTRAINTS;
CREATE TABLE MB_USER_ROLE
(
  ID     NVARCHAR2(36) NOT NULL,
  CAPTION  NVARCHAR2(32)  NOT NULL,
  CONSTRAINTS PK_USER_ROLE PRIMARY KEY(ID) USING INDEX TABLESPACE tbs_pk_idx
);
/

-- 用户权限关系表 MB_USER_ROLE_RELATION
-- 删除表 DROP TABLE MB_USER_ROLE_RELATION CASCADE CONSTRAINTS;
CREATE TABLE MB_USER_ROLE_RELATION
(
  ROLEID  NVARCHAR2(36) NOT NULL,
  USERID  NVARCHAR2(36) NOT NULL,
  DISABLEDATE DATE,
  CONSTRAINTS FK_USER_INFO_ID FOREIGN KEY (USERID) REFERENCES MB_USER(ID) ON DELETE CASCADE,
  CONSTRAINTS FK_USER_ROLE_ID FOREIGN KEY (ROLEID) REFERENCES MB_USER_ROLE(ID) ON DELETE CASCADE
);
/

-- 用户权限表 MB_USER_PRIVILEGE
-- 删除表 DROP TABLE MB_USER_PRIVILEGE CASCADE CONSTRAINTS;
CREATE TABLE MB_USER_PRIVILEGE
(
  CODE     NVARCHAR2(16) NOT NULL,
  NAME     NVARCHAR2(32)  NOT NULL,
  CONSTRAINTS PK_USER_PRIVILEGE PRIMARY KEY(CODE) USING INDEX TABLESPACE tbs_pk_idx
);
/

-- 权限角色关系表 MB_USER_ROLE_PRIVILEGE
-- 删除表 DROP TABLE MB_USER_ROLE_PRIVILEGE CASCADE CONSTRAINTS;
CREATE TABLE MB_USER_ROLE_PRIVILEGE
(
  PRIVILEGECODE  NVARCHAR2(16)  NOT NULL,
  ROLEID NVARCHAR2(36) NOT NULL,
  CONSTRAINTS PK_USER_ROLE_PRIVILEGE PRIMARY KEY(PRIVILEGECODE,ROLEID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_USER_PRI_CODE FOREIGN KEY (PRIVILEGECODE) REFERENCES MB_USER_PRIVILEGE(CODE) ON DELETE CASCADE,
  CONSTRAINTS FK_USER_ROLE FOREIGN KEY (ROLEID) REFERENCES MB_USER_ROLE(ID) ON DELETE CASCADE
);
/

-- 用户钱包表 MB_USER_WALLET
-- 删除表 DROP TABLE MB_USER_WALLET CASCADE CONSTRAINTS;
CREATE TABLE MB_USER_WALLET
(
  USERID     NVARCHAR2(36) not null,
  Balance NUMBER(16,2) DEFAULT 0,
  PASSWORD  NVARCHAR2(32),
  BEAN    NUMBER DEFAULT 0,
  SILVER  NUMBER DEFAULT 0,
  GOLD    NUMBER DEFAULT 0,
  DIAMOND NUMBER DEFAULT 0,
  CONSTRAINTS PK_USER_WALLET_ID PRIMARY KEY (USERID) USING INDEX TABLESPACE tbs_pk_idx
);
/

-- 用户钱包流水表 MB_USER_FLOW
-- 删除表 DROP TABLE MB_USER_FLOW CASCADE CONSTRAINTS;
CREATE TABLE MB_USER_FLOW
(
  USERID        NVARCHAR2(36) NOT NULL,
  FLOWTYPE      NUMBER(2) NOT NULL,
  AMOUNTCHANGE  NUMBER(16,2) NOT NULL,
  CREATEDATE    DATE DEFAULT SYSDATE,
  RESUME        NVARCHAR2(32),
  BEFORETOTAL   NUMBER(16,2) NOT NULL
);
/

-- 用户站内信表 MB_USER_MESSAGE
-- 删除表 DROP TABLE MB_USER_MESSAGE CASCADE CONSTRAINTS;
CREATE TABLE MB_USER_MESSAGE
(
  ID         NVARCHAR2(36) NOT NULL,
  CREATEDATE DATE DEFAULT SYSDATE,
  INVALIDATE DATE,
  TITLE      NVARCHAR2(40) NOT NULL,
  CONTENT    NVARCHAR2(1024) NOT NULL,
  CODE       NVARCHAR2(16),
  CONSTRAINTS PK_USER_MESSAGE PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx
);
/

-- 用户站内信关系表 MB_MESSAGE_USER_RELATION
-- 删除表 DROP TABLE MB_MESSAGE_USER_RELATION CASCADE CONSTRAINTS;
CREATE TABLE MB_MESSAGE_USER_RELATION
(
  ID      NVARCHAR2(36) NOT NULL,
  USERID  NVARCHAR2(36) NOT NULL,
  MESSAGEID  NVARCHAR2(36) NOT NULL,
  READED  NUMBER(1) DEFAULT 0 CONSTRAINT CHK_MSG_USER_READ CHECK (READED IN (0,1)),
  CREATEDATE DATE NOT NULL,
  INVALIDATE DATE,
  CONSTRAINTS PK_MSG_USER_REL_ID PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_MSG_USER_ID FOREIGN KEY (USERID) REFERENCES MB_USER(ID) ON DELETE CASCADE,
  CONSTRAINTS FK_MSG_USER_MESSAGEID FOREIGN KEY (MESSAGEID) REFERENCES MB_USER_MESSAGE(ID) ON DELETE CASCADE
);
/

-- 用户微信信息表 MB_WEIXIN_USER
-- 删除表 DROP TABLE MB_WEIXIN_USER CASCADE CONSTRAINTS;
CREATE TABLE MB_WEIXIN_USER
(
  USERID    NVARCHAR2(36) NOT NULL,
  WEIXINID	NVARCHAR2(64) NOT NULL,
  CONSTRAINTS PK_WEIXIN_USER PRIMARY KEY (USERID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_WEIXIN_USER_ID FOREIGN KEY (USERID) REFERENCES MB_USER(ID) ON DELETE CASCADE
);
/

-- 用户充值信息表 MB_USER_PAY
-- 删除表 DROP TABLE MB_USER_PAYCASCADE CONSTRAINTS;
CREATE TABLE MB_USER_PAY
(
   ID  NVARCHAR2(36) NOT NULL,
   USERID NVARCHAR2(36) NOT NULL,
   AMOUNT NUMBER(16,2) NOT NULL,
   CREATEDATE DATE DEFAULT SYSDATE,
   TYPE   NUMBER(1) NOT NULL,
   RESUME NVARCHAR2(64),
   BUSINESSID NVARCHAR2(36) DEFAULT 0,
   ORDERNO NVARCHAR2(24),
   STATUS  NUMBER(1) DEFAULT 0,
   CONSTRAINTS PK_USER_PAY PRIMARY KEY(ID) USING INDEX TABLESPACE tbs_pk_idx
);
/

-- 商家参数关联表 MB_PARAM_SUIT
-- 删除表 DROP TABLE MB_PARAM_SUIT CASCADE CONSTRAINTS;
CREATE TABLE MB_PARAM_SUIT
(
  ID       NVARCHAR2(36) NOT NULL,
  RESUME   NVARCHAR2(32)  NOT NULL,
  CONSTRAINTS PK_PARAM_SUIT_ID PRIMARY KEY(ID) USING INDEX TABLESPACE tbs_pk_idx
);
/

-- 商家权限表 MB_BUSINESS_PRIVILEGE
-- 删除表 DROP TABLE MB_BUSINESS_PRIVILEGE CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_PRIVILEGE
(
  CODE     NVARCHAR2(16) NOT NULL,
  CAPTION  NVARCHAR2(32)  NOT NULL,
  CONSTRAINTS PK_BUSINESS_PRIVILEGE PRIMARY KEY(CODE) USING INDEX TABLESPACE tbs_pk_idx
);
/
INSERT INTO MB_BUSINESS_PRIVILEGE VALUES('P001','线下联盟权限');
INSERT INTO MB_BUSINESS_PRIVILEGE VALUES('P002','线上商城权限');
INSERT INTO MB_BUSINESS_PRIVILEGE VALUES('P003','查询联盟展现权限');
INSERT INTO MB_BUSINESS_PRIVILEGE VALUES('P004','上级付款权限');


-- 商家角色表 MB_BUSINESS_ROLE
-- 删除表 DROP TABLE MB_BUSINESS_ROLE CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_ROLE
(
  ID     NVARCHAR2(36) NOT NULL,
  CAPTION  NVARCHAR2(32)  NOT NULL,
  CONSTRAINTS PK_BUSINESS_ROLE PRIMARY KEY(ID) USING INDEX TABLESPACE tbs_pk_idx
);
/

-- 权限角色关系表 MB_BUSINESS_ROLE_PRIVILEGE
-- 删除表 DROP TABLE MB_BUSINESS_ROLE_PRIVILEGE CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_ROLE_PRIVILEGE
(
  PRIVILEGECODE  NVARCHAR2(16)  NOT NULL,
  ROLEID NVARCHAR2(36) NOT NULL,
  CONSTRAINTS PK_BUSINESS_ROLE_PRIVILEGE PRIMARY KEY(PRIVILEGECODE,ROLEID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_PRIVILEGE_CODE FOREIGN KEY (PRIVILEGECODE) REFERENCES MB_BUSINESS_PRIVILEGE(CODE) ON DELETE CASCADE,
  CONSTRAINTS FK_BUSINESS_ROLE FOREIGN KEY (ROLEID) REFERENCES MB_BUSINESS_ROLE(ID) ON DELETE CASCADE
);
/

-- 商家基本信息表 MB_BUSINESS
-- 删除表 DROP TABLE MB_BUSINESS CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS
(
  ID     NVARCHAR2(36) NOT NULL,
  PID    NVARCHAR2(36) NOT NULL,
  SHORTNAME NVARCHAR2(32) NOT NULL,
  NAME  NVARCHAR2(32) NOT NULL,
  INDATE DATE DEFAULT SYSDATE,
  SUITID NVARCHAR2(36),
  RESUME NVARCHAR2(64),
  STATUS NUMBER(1) DEFAULT 0,
  TYPE NUMBER(3) NOT NULL,
  PROVINCEID NUMBER,
  TOWNID   NUMBER,
  ADDRAREA NUMBER,
  ADDRSTREET NVARCHAR2(64),
  POINTLNG NUMBER(10,6),
  POINTLAT NUMBER(10,6),
  PAYDATE  DATE DEFAULT SYSDATE,
  DISCOUNT NUMBER(3,2),
  BILLTYPE NUMBER(1) DEFAULT 1,
  CONSTRAINTS PK_BUSINESS_ID PRIMARY KEY(ID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_SUIT_ID FOREIGN KEY (SUITID) REFERENCES MB_PARAM_SUIT(ID) ON DELETE SET NULL
);
/

-- 商家权限关系表 MB_BUSINESS_ROLE_RELATION
-- 删除表 DROP TABLE MB_BUSINESS_ROLE_RELATION CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_ROLE_RELATION
(
  ROLEID  NVARCHAR2(36) NOT NULL,
  BUSINESSID  NVARCHAR2(36) NOT NULL,
  DISABLEDATE DATE,
  CONSTRAINTS FK_BUSINESS_INFO_ID FOREIGN KEY (BUSINESSID) REFERENCES MB_BUSINESS(ID) ON DELETE CASCADE,
  CONSTRAINTS FK_BUSINESS_ROLE_ID FOREIGN KEY (ROLEID) REFERENCES MB_BUSINESS_ROLE(ID) ON DELETE CASCADE
);
/

-- 商家联系人表 MB_BUSINESS_CONTRACT
-- 删除表 DROP TABLE MB_BUSINESS_CONTRACT CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_CONTRACT
(
  ID      NVARCHAR2(36) NOT NULL,
  NAME   NVARCHAR2(16)  NOT NULL,
  CALLNUMBER NVARCHAR2(16),
  PHONENUMBER NVARCHAR2(16) NOT NULL,
  ADDRAREAID NUMBER,
  ADDRSTREET NVARCHAR2(32),
  SEX NUMBER(1),
  COMPANY NVARCHAR2(32),
  POST NVARCHAR2(16),
  QQ NVARCHAR2(16),
  BUSINESSID  NVARCHAR2(36) NOT NULL,
  TYPE NUMBER(1) NOT NULL,
  MAIL NVARCHAR2(32) NOT NULL,
  DEL  NUMBER(1) DEFAULT 0,
  CONSTRAINTS PK_BUSINESS_CONTRACT_ID PRIMARY KEY(ID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_BUS_INFO_ID FOREIGN KEY (BUSINESSID) REFERENCES MB_BUSINESS(ID) ON DELETE CASCADE
);
/
-- 商家包邮优惠信息表 MB_BUSINESS_DISCOUNT
-- 删除表 DROP TABLE MB_BUSINESS_DISCOUNT CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_DISCOUNT
(
  ID      NVARCHAR2(36) NOT NULL,
  BUSINESSID   NVARCHAR2(16) NOT NULL,
  TYPE    NUMBER(1) NOT NULL,
  POSTAGEMONEY NUMBER(16,2),
  STARTDATE DATE NOT NULL,
  ENDDATE   DATE NOT NULL,
  CONSTRAINTS PK_GOODS_DISCOUNT_ID PRIMARY KEY(ID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_BUSINESS_ID FOREIGN KEY (BUSINESSID) REFERENCES MB_BUSINESS(ID) ON DELETE CASCADE
);
/

-- 商家账号权限表 MB_BUSINESS_PRIVILEGE
-- 删除表 DROP TABLE MB_BUSINESS_PRIVILEGE CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESSER_PRIVILEGE
(
  CODE     NVARCHAR2(16) NOT NULL,
  CAPTION  NVARCHAR2(32)  NOT NULL,
  CONSTRAINTS PK_BUSINESSER_PRIVILEGE PRIMARY KEY(CODE) USING INDEX TABLESPACE tbs_pk_idx
);
/

-- 商家账号角色表 MB_BUSINESS_ROLE
-- 删除表 DROP TABLE MB_BUSINESS_ROLE CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESSER_ROLE
(
  ID      NVARCHAR2(36) NOT NULL,
  CAPTION  NVARCHAR2(32)  NOT NULL,
  BUSINESSID NVARCHAR2(36) DEFAULT 0,
  TYPE     NUMBER(1) DEFAULT 0,
  CONSTRAINTS PK_BUSINESSER_ROLE PRIMARY KEY(ID) USING INDEX TABLESPACE tbs_pk_idx
);
/

-- 商家账号权限角色关系表 MB_BUSINESS_ROLE_PRIVILEGE
-- 删除表 DROP TABLE MB_BUSINESS_ROLE_PRIVILEGE CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESSER_ROLE_PRIVILEGE
(
  PRIVILEGECODE  NVARCHAR2(16)  NOT NULL,
  ROLEID  NVARCHAR2(36) NOT NULL,
  CONSTRAINTS PK_BUSINESSER_ROLE_PRIVILEGE PRIMARY KEY(PRIVILEGECODE,ROLEID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_PRIVILEGEER_CODE FOREIGN KEY (PRIVILEGECODE) REFERENCES MB_BUSINESSER_PRIVILEGE(CODE) ON DELETE CASCADE,
  CONSTRAINTS FK_BUSINESSER_ROLE FOREIGN KEY (ROLEID) REFERENCES MB_BUSINESSER_ROLE(ID) ON DELETE CASCADE
);
/

-- 商家账号表 MB_BUSINESSER
-- 删除表 DROP TABLE MB_BUSINESSERCASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESSER
(
  ID      NVARCHAR2(36) NOT NULL,
  ACCOUNT NVARCHAR2(24) NOT NULL,
  PASSWORD NVARCHAR2(32) NOT NULL,
  BUSINESSID  NVARCHAR2(36) NOT NULL,
  POST NVARCHAR2(16),
  NAME NVARCHAR2(16) NOT NULL,
  STATUS NUMBER(1) DEFAULT 0,
  TYPE   NUMBER(1) DEFAULT 0,
  DEL  NUMBER(1) DEFAULT 0,
  LASTLOGINDATE DATE,
  CONSTRAINTS PK_BUSINESSER_ID PRIMARY KEY(ID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_BUSINESS_INFOID FOREIGN KEY (BUSINESSID) REFERENCES MB_BUSINESS(ID) ON DELETE CASCADE
);
/

-- 商家人员联系信息表 MB_BUSINESSER_CONTRACT
-- 删除表 DROP TABLE MB_BUSINESSER_CONTRACT CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESSER_CONTRACT
(
  ID      NVARCHAR2(36) NOT NULL,
  PHONE   NVARCHAR2(16) UNIQUE NOT NULL,
  EMAIL   NVARCHAR2(32),
  BUSINESSERID NVARCHAR2(36) NOT NULL,
  CONSTRAINTS PK_BUSINESSER_CONTRACT PRIMARY KEY(ID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_BUSINESSER_ID FOREIGN KEY (BUSINESSERID) REFERENCES MB_BUSINESSER(ID) ON DELETE CASCADE
);
/

-- 商家账号角色关系表 MB_BUSINESS_ROLE_RELATION
-- 删除表 DROP TABLE MB_BUSINESS_ROLE_RELATION CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESSER_ROLE_RELATION
(
  ROLEID  NVARCHAR2(36) NOT NULL,
  BUSINESSERID  NVARCHAR2(36) NOT NULL,
  CONSTRAINTS PK_BUSINESSER_ROLE_RELATION PRIMARY KEY(BUSINESSERID,ROLEID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_BUSINESSER_INFO_ID FOREIGN KEY (BUSINESSERID) REFERENCES MB_BUSINESSER(ID) ON DELETE CASCADE,
  CONSTRAINTS FK_BUSINESSER_ROLE_ID FOREIGN KEY (ROLEID) REFERENCES MB_BUSINESSER_ROLE(ID) ON DELETE CASCADE
);
/

-- 商家分类表 MB_BUSINESS_CLASSIFY
-- 删除表 DROP TABLE MB_BUSINESS_CLASSIFY CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_CLASSIFY
(
  ID      NVARCHAR2(36) NOT NULL,
  PID    NVARCHAR2(36) NOT NULL,
  CAPTION NVARCHAR2(32) NOT NULL,
  CONSTRAINTS PK_BUSINESS_CLASSIFY_ID PRIMARY KEY(ID) USING INDEX TABLESPACE tbs_pk_idx
);
/

-- 商家分类对应表 MB_BUSINESS_ROLE_RELATION
-- 删除表 DROP TABLE MB_BUSINESS_ROLE_RELATION CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_CLASSIFY_RELATION
(
  BUSINESSID    NVARCHAR2(36) NOT NULL,
  CLASSIFYID    NVARCHAR2(36) NOT NULL,
  CONSTRAINTS PK_BUSINESS_CLASSIFY_REL_ID PRIMARY KEY(BUSINESSID,CLASSIFYID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_BUSINESS_INFO FOREIGN KEY (BUSINESSID) REFERENCES MB_BUSINESS(ID) ON DELETE CASCADE,
  CONSTRAINTS FK_BUSINESS_CLASSIFY_ID FOREIGN KEY (CLASSIFYID) REFERENCES MB_BUSINESS_CLASSIFY(ID) ON DELETE CASCADE
);
/

-- 商家钱包表 MB_BUSINESS_WALLET
-- 删除表 DROP TABLE MB_BUSINESS_WALLET CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_WALLET
(
  BUSINESSID     NVARCHAR2(36) not null,
  Balance NUMBER(16,2) DEFAULT 0,
  PASSWORD  NVARCHAR2(32),
  CONSTRAINTS PK_BUSINESS_WALLET_ID PRIMARY KEY (BUSINESSID) USING INDEX TABLESPACE tbs_pk_idx
);
/


-- 商家钱包流水表 MB_BUSINESS_FLOW
-- 删除表 DROP TABLE MB_BUSINESS_FLOW CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_FLOW
(
  BUSINESSID     NVARCHAR2(36) not null,
  AMOUNTCHANGE  NUMBER(16,2) NOT NULL,
  CREATEDATE    DATE DEFAULT SYSDATE,
  RESUME        NVARCHAR2(32),
  BEFORETOTAL   NUMBER(16,2) NOT NULL,
  FLOWTYPE      NUMBER(3) NOT NULL
);
/

-- 商家站内信表 MB_BUSINESS_MESSAGE
-- 删除表 DROP TABLE MB_BUSINESS_MESSAGE CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_MESSAGE
(
  ID         NVARCHAR2(36) NOT NULL,
  CREATEDATE DATE DEFAULT SYSDATE,
  INVALIDATE DATE,
  TITLE      NVARCHAR2(40) NOT NULL,
  CONTENT    NVARCHAR2(1024) NOT NULL,
  CODE       NVARCHAR2(16),
  CONSTRAINTS PK_BUSINESS_MESSAGE PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx
);
/

-- 商家站内信关系表 MB_MESSAGE_BUSINESS_RELATION
-- 删除表 DROP TABLE MB_MESSAGE_BUSINESS_RELATION CASCADE CONSTRAINTS;
CREATE TABLE MB_MESSAGE_BUSINESS_RELATION
(
  ID      NVARCHAR2(36) NOT NULL,
  BUSINESSID   NVARCHAR2(36) NOT NULL,
  MESSAGEID  NVARCHAR2(36) NOT NULL,
  READED  NUMBER(1) DEFAULT 0 CONSTRAINT CHK_MSG_BUSINESS_READ CHECK (READED IN (0,1)),
  CREATEDATE DATE NOT NULL,
  INVALIDATE DATE,
  CONSTRAINTS PK_MSG_BUSINESS_REL_ID PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_MSG_BUSINESS_ID FOREIGN KEY (BUSINESSID) REFERENCES MB_BUSINESS(ID) ON DELETE CASCADE,
  CONSTRAINTS FK_MSG_BUSINESS_MESSAGEID FOREIGN KEY (MESSAGEID) REFERENCES MB_BUSINESS_MESSAGE(ID) ON DELETE CASCADE
);
/

--用户购买记录表 MB_USER_BUY_RECORD
--删除表 DROP TABLE MB_USER_BUY_RECORD CASCADE CONSTRAINTS;
CREATE TABLE MB_USER_BUY_RECORD
(
  ORDERNO    NVARCHAR2(24) NOT NULL,
  USERID     NVARCHAR2(36) NOT NULL,
  FEE        NUMBER(16,2) NOT NULL,
  CREATEDATE DATE NOT NULL,
  STATUS     NUMBER(1) NOT NULL,
  CONSTRAINTS PK_USER_BUY_RECORD PRIMARY KEY (ORDERNO) USING INDEX TABLESPACE tbs_pk_idx
);
/

--商家账单表 MB_BUSINESS_AP_PER
--删除表 DROP TABLE MB_BUSINESS_AP_PER CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_AP_PER
(
  ID    NVARCHAR2(36) NOT NULL,
  BUSINESSID NVARCHAR2(36) NOT NULL,
  FEE        NUMBER(16,2) NOT NULL,
  STARTDATE  DATE NOT NULL,
  ENDDATE    DATE NOT NULL,
  TYPE       NUMBER(1) NOT NULL,
  CONSTRAINTS PK_BUSINESS_AP_PER_ID PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx
);
/

--商家支付账单表 MB_BILL
--删除表 DROP TABLE MB_BILL CASCADE CONSTRAINTS;
CREATE TABLE MB_BILL
(
  ID    NVARCHAR2(36) NOT NULL,
  BUSINESSID NVARCHAR2(36) NOT NULL,
  STARTDATE  DATE NOT NULL,
  ENDDATE    DATE NOT NULL,
  FEE        NUMBER(16,2) NOT NULL,
  PAYFEE        NUMBER(16,2)    NOT NULL,
  TYPE       NUMBER(2) DEFAULT 0,
  CONSTRAINTS PK_BILL_ID PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx
);
/

-- 短信模版表 MB_SMS_TEMPLATE
-- 删除表 DROP TABLE MB_SMS_TEMPLATE CASCADE CONSTRAINTS;
CREATE TABLE MB_SMS_TEMPLATE
(
  ID    NVARCHAR2(36) NOT NULL,
  CAPTION   NVARCHAR2(128) NOT NULL,
  CODE    NVARCHAR2(12) NOT NULL,
  RESUME  NVARCHAR2(32), 
  SMSTYPE NUMBER NOT NULL,
  CONSTRAINTS PK_SMS_TEMPLATE PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx
);
/
---------------------------------------------------------------------
-- 邮件验证操作码表 MB_MAIL_TEMP
-- 删除表 DROP TABLE MB_MAIL_TEMP CASCADE CONSTRAINTS;
CREATE TABLE MB_MAIL_TEMP
(
  ID      NVARCHAR2(36) NOT NULL,
  CAPTION NVARCHAR2(512) NOT NULL,
  CODE    NVARCHAR2(12)  NOT NULL,
  RESUME  NVARCHAR2(32),
  MAILTYPE NUMBER NOT NULL,
  CONSTRAINTS PK_MAIL_AFFIRM_OPT PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx
  );
/
-- 添加列描述 
COMMENT ON COLUMN MB_MAIL_TEMP.ID IS '短信操作码';
COMMENT ON COLUMN MB_MAIL_TEMP.CAPTION IS '短信描述';

-- MB_AD_RESOURCE
-- 删除表 DROP TABLE MB_AD_RESOURCE CASCADE CONSTRAINTS;
CREATE TABLE MB_AD_RESOURCE
(
  ID    NVARCHAR2(36) NOT NULL,
  LOCALID       NVARCHAR2(8) NOT NULL,
  LIMITDATE  DATE NOT NULL,
  ENABLE   NUMBER(1) DEFAULT 1 CONSTRAINT CHK_AD_RESOURCE_ENABLE CHECK (ENABLE IN (0,1)),
  BUSINESSID     NVARCHAR2(36),
  CONPATH    NVARCHAR2(128),
  REMARK      NVARCHAR2(50),
  STARTDATE  DATE,
  PAGENAME   NVARCHAR2(32),
  IMAGESPATH NVARCHAR2(256),
  ADSERIALNO NUMBER,
  CONSTRAINTS PK_AD_RESOURCE PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx
);
/

-- 支付参数表 MB_PAY_PARAMER
-- 删除表 DROP TABLE MB_PAY_PARAMER CASCADE CONSTRAINTS;
CREATE TABLE MB_PAY_PARAMER
(
  ID      NVARCHAR2(36) NOT NULL,
  KEY    NVARCHAR2(16) NOT NULL,
  VALUE  NUMBER NOT NULL,
  RESUME    NVARCHAR2(32),
  SUITID    NVARCHAR2(16) NOT NULL,
  DEVIATION NUMBER NOT NULL,
  CONSTRAINTS PK_PAY_PARAMER_ID PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx
);
/


-- 商家指定付款表 MB_PAY_ASSIGN
-- 删除表 DROP TABLE MB_PAY_ASSIGN CASCADE CONSTRAINTS;
CREATE TABLE MB_PAY_ASSIGN
(
  ID      NVARCHAR2(36) NOT NULL,
  BUSINESSID NVARCHAR2(36) NOT NULL,
  CONSTRAINTS PK_PAY_ASSIGN_ID PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_PAY_ASSIGN_ID FOREIGN KEY (BUSINESSID) REFERENCES  MB_BUSINESS (ID) on delete cascade
);
/

-- 商家关系表 MB_BUSINESS_RELATION
-- 删除表 DROP TABLE MB_BUSINESS_RELATION CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_RELATION
(
  ID      NVARCHAR2(36) NOT NULL,
  BUSINESSID NVARCHAR2(36) NOT NULL,
  HIGHBUSINESSID NVARCHAR2(36) NOT NULL,
  CONSTRAINTS PK_BUSINESS_RELATION_ID PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_BUSINESS_RELATION_ID FOREIGN KEY (BUSINESSID) REFERENCES  MB_BUSINESS (ID) on delete cascade,
  CONSTRAINTS FK_HIGHBUS_RELATION_ID FOREIGN KEY (HIGHBUSINESSID) REFERENCES  MB_BUSINESS (ID) on delete cascade
);
/

-- 商家登录记录表 MB_BUSINESS_LOGIN_RECORD
-- 删除表 DROP TABLE MB_BUSINESS_LOGIN_RECORD CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_LOGIN_RECORD
(
  ID      NVARCHAR2(36) NOT NULL,
  LOGINTIME DATE DEFAULT SYSDATE,
  BUSINESSERID NVARCHAR2(36) NOT NULL,
  STATUS   NUMBER(1) NOT NULL,
  IP      NVARCHAR2(24),
  CONSTRAINTS PK_LOGIN_RECORD_ID PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx
);
/

-- 商家支付明细表 MB_BUSINESS_PAY
-- 删除表 DROP TABLE MB_BUSINESS_PAY CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_PAY
(
  ID      NVARCHAR2(36) NOT NULL,
  BILLID  NVARCHAR2(36) NOT NULL,
  BUSINESSID NVARCHAR2(36) NOT NULL,
  BUSINESSERID NVARCHAR2(36) NOT NULL,
  PAYVALUE NUMBER(16,2) NOT NULL,
  CREATEDATE DATE DEFAULT SYSDATE,
  RESUME   NVARCHAR2(32),
  CONSTRAINTS PK_BUSINESS_PAY_ID PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx
);
/
--商家地址表 MB_BUSINESS_ADDRESS
-- 删除表 DROP TABLE MB_BUSINESS_ADDRESS CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_ADDRESS
(
  ID	      NVARCHAR2(36) NOT NULL,
  BUSINESSID  NVARCHAR2(36) NOT NULL,
  AREAID  NVARCHAR2(36) NOT NULL,
  CODE    NVARCHAR2(8) NOT NULL,
  ADDRESS NVARCHAR2(64) NOT NULL,
  NAME    NVARCHAR2(16) NOT NULL,
  TEL     NVARCHAR2(16),
  MOBILE  NVARCHAR2(16), 
  DEFAULTADDRESS DATE,
  CONSTRAINTS PK_BRAND_ADDRESS_ID PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx
);
/

------------------------------------------------------------------
-- 在对订单表 MB_ORDER_INQUEUE
-- 删除表 DROP TABLE MB_ORDER_UNACTIVATE CASCADE CONSTRAINTS;

CREATE TABLE MB_ORDER_INQUEUE
(
  RECORDNO      NUMBER NOT NULL,
  QUEUERECORDID NUMBER NOT NULL,
  ORDERNO  NVARCHAR2(24) NOT NULL,
  BUSINESSNAME  NVARCHAR2(36) NOT NULL,
  USERID  NVARCHAR2(36) not null,
  FEE    NUMBER(16,2) NOT NULL,
  ORDERCREATEDATE DATE NOT NULL,
  INQUEUEDATE DATE DEFAULT SYSDATE,
  REMARK  NVARCHAR2(24),  
  REBACKFEE NUMBER(16,2) not null,
  STORAGEDATE DATE,
  BUSINESSERID  NVARCHAR2(36) NOT NULL,
  STATUS      NUMBER(1) DEFAULT 0,
  ORIGIN      NUMBER(1) DEFAULT 0,
  CONSTRAINTS PK_ORDER_INQUEUE PRIMARY KEY (ORDERNO) USING INDEX --TABLESPACE idx_mb_order_inqueue
) --TABLESPACE tbs_lm_mb_order_inqueue;
/

-- 商户银行卡信息表 MB_BUSINESS_CARD
-- 删除表 DROP TABLE MB_BUSINESS_CARD CASCADE CONSTRAINTS;
CREATE TABLE MB_BUSINESS_CARD
(
  ID      NVARCHAR2(36) NOT NULL,
  BUSINESSID   NVARCHAR2(36) NOT NULL,
  OPENCARDAREA   NVARCHAR2(32),
  OPENCARDBANK   NVARCHAR2(32) NOT NULL,
  BANKBRANCH     NVARCHAR2(64) NOT NULL,
  BANKCARDNUM    NVARCHAR2(24) NOT NULL,
  BANKCARDKEEPER NVARCHAR2(16)   NOT NULL,
  AREAID         NUMBER  NOT NULL,
  STATUS         NUMBER  DEFAULT 0,
  DEL  NUMBER(1) DEFAULT 0,
  CONSTRAINTS PK_BRAND_CARD_INFO_ID PRIMARY KEY (ID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_BRAND_CARD_INFO_ID FOREIGN KEY (BUSINESSID) REFERENCES MB_BUSINESS(ID) ON DELETE CASCADE
);
/

-- 付款方式申请表 MB_COMPLAIN
-- 删除表 DROP TABLE MB_COMPLAIN CASCADE CONSTRAINTS;
CREATE TABLE MB_PAYTYPE_APPLY
(
  BUSINESSID  NVARCHAR2(36) NOT NULL,
  NEWPAYTYPE NUMBER(1) NOT NULL CONSTRAINT CHK_NEWPAYTYPE CHECK (NEWPAYTYPE IN (1,2)),
  CONSTRAINTS PK_PAYTYPE_APPLY PRIMARY KEY (BUSINESSID) USING INDEX TABLESPACE tbs_pk_idx,
  CONSTRAINTS FK_PAYTYPE_BUS_ID foreign key (BUSINESSID) REFERENCES MB_BUSINESS (ID) ON DELETE CASCADE
);
/

-- 用户活动表 MB_USER_ACTIVITY
-- 删除表 DROP TABLE MB_USER_ACTIVITY CASCADE CONSTRAINTS;
CREATE TABLE MB_USER_ACTIVITY
(
  ID      NVARCHAR2(36) NOT NULL,
  PHONE   NVARCHAR2(16) UNIQUE NOT NULL,
  ACTIVITYID NVARCHAR2(36),
  ISVALID NUMBER(1) DEFAULT 0,
  CONSTRAINTS PK_USER_ACTIVITY PRIMARY KEY(ID) USING INDEX TABLESPACE tbs_pk_idx
);
/

-- 会员价表 MB_VIP_PRICE
-- 删除表 DROP TABLE MB_VIP_PRICECASCADE CONSTRAINTS;
CREATE TABLE MB_VIP_PRICE
(
  ID      NVARCHAR2(36) NOT NULL,
  BUSINESSID NVARCHAR2(36) NOT NULL,
  STARTTIME DATE NOT NULL,
  ENDTIME   DATE NOT NULL,
  ENABLE    NUMBER(1) NOT NULL,
  PRICE     NUMBER(16,2) NOT NULL,
  TYPE      NUMBER(1) NOT NULL,
  RESUME    NVARCHAR2(64),
  CONSTRAINTS PK_VIP_PRICE PRIMARY KEY(ID) USING INDEX TABLESPACE tbs_pk_idx
);
/



